(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Set' object has no attribute 'show_list'"
p3
sS'layer'
p4
S'/home/acuevas/Documents/College/ThirdYear/CS183/web2py/applications/FinalProject/controllers/api.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f85f00ec430, file "/home/acuevas/Documents/College/ThirdYear/CS183/web2py/applications/FinalProject/controllers/api.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/acuevas/Documents/College/ThirdYear/CS183/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/acuevas/Documents/College/ThirdYear/CS183/web2py/applications/FinalProject/controllers/api.py", line 85, in <module>\n  File "/home/acuevas/Documents/College/ThirdYear/CS183/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/acuevas/Documents/College/ThirdYear/CS183/web2py/applications/FinalProject/controllers/api.py", line 82, in add_favorites\n    db(q).show_list.update(favorite=True);\nAttributeError: \'Set\' object has no attribute \'show_list\'\n'
p11
s.